version: "3.3"

services:
  mealie: 
    #image: ghcr.io/mealie-recipes/mealie:v2.8.0
    image: hkotel/mealie:v2.8.0 
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/max/docker-services/config/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=https://mealie.shashy.org
    networks:
      - proxy_network 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`mealie.shashy.org`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls=true"
volumes:
  mealie-data:

networks:
  proxy_network:
    external: true

