version: "3.3"

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: always
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik:/etc/traefik:ro"
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.shashy.org`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"

networks:
  proxy_network:
    name: proxy_network

