services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.5.56:3000
      PUID: ${PUID}
      PGID: ${GUID}
    ports:
      - 3000:3000
    volumes:
      - /opt/docker-services/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
        #networks:
        #  - proxy_network
        #labels:
        #  - "traefik.enable=true"
        #  - "traefik.http.routers.homepage.rule=Host(`home.shashy.org`)"
        #  - "traefik.http.routers.homepage.entrypoints=websecure"
        #  - "traefik.http.routers.homepage.tls=true"

        #networks:
        #  proxy_network:
        #    external: true
