services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8082:8080
    env_file: .env

    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glance.shashy.org`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.tls=true"

networks:
  proxy_network:
    external: true
